#!/bin/sh

# 检查是否加载了 mtkhnat 模块
if [ -n "$(lsmod | grep mtkhnat)" ]; then
    uci set turboacc.config.sw_flow='0'
    uci set turboacc.config.hw_flow='0'
fi

# 提交更改
uci commit turboacc

exit 0

