#!/bin/sh

[ ! -f '/etc/rpcd_10_system.js' ] || \
	mv -f '/etc/rpcd_10_system.js' '/www/luci-static/resources/view/status/include/10_system.js'
[ ! -f '/etc/rpcd_20_memory.js' ] || \
	mv -f '/etc/rpcd_20_memory.js' '/www/luci-static/resources/view/status/include/20_memory.js'
[ ! -f '/etc/rpcd_30_network.js' ] || \
	mv -f '/etc/rpcd_30_network.js' '/www/luci-static/resources/view/status/include/30_network.js'
#[ ! -f '/etc/rpcd_luci-base.json' ] || \
#	mv -f '/etc/rpcd_luci-base.json' '/usr/share/luci/menu.d/luci-base.json'
[ ! -f '/etc/rpcd_luci' ] || \
	mv -f '/etc/rpcd_luci' '/usr/share/rpcd/ucode/luci'
/etc/init.d/rpcd restart

exit 0



